// Netlify build script — generates public/config.js from environment variables
// Run automatically during Netlify build via netlify.toml build command

const fs   = require("fs");
const path = require("path");

const key   = process.env.GROQ_API_KEY   || "";
const model = process.env.GROQ_MODEL     || "openai/gpt-oss-120b";
const url   = process.env.GROQ_URL       || "https://api.groq.com/openai/v1/chat/completions";

if (!key) {
    console.warn("[generate-config] WARNING: GROQ_API_KEY env var is not set. AI features will be disabled.");
}

const content = `// Auto-generated by scripts/generate-config.js during Netlify build.
// Do not edit manually. Set GROQ_API_KEY in Netlify environment variables.
window.ALGOFORGE_CONFIG = {
    GROQ_API_KEY: "${key}",
    GROQ_MODEL:   "${model}",
    GROQ_URL:     "${url}"
};
`;

const outPath = path.join(__dirname, "..", "public", "config.js");
fs.writeFileSync(outPath, content, "utf8");
console.log("[generate-config] public/config.js generated successfully.");
console.log("[generate-config] Key present:", key.length > 0 ? `YES (${key.length} chars)` : "NO");
